name: Deploy to EC2

on:
  push:
    branches:
      - main  # Deploy when pushing to the 'branch' branch (modify as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
    
    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to EC2
      run: |
        ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          source ec2_env/bin/activate
          cd django-form-app
          git pull origin main
          pip install -r requirements.txt
          fuser -k 8000/tcp
          sudo systemctl restart nginx
          pkill gunicorn
          nohup gunicorn --bind 0.0.0.0:8000 django_form_app.wsgi:application > gunicorn.log 2>&1 &
        EOF